fails:Kernel.catch accepts an object as an argument
fails:Kernel.catch yields a new, unique object when called without arguments
fails:Kernel#catch is a private method
fails:Kernel.catch does not match objects that are not exactly the same
